In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2, 3))

In [3]:
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
torch_data = torch.from_numpy(np_data)
torch_data


 0  1  2
 3  4  5
[torch.LongTensor of size 2x3]

In [5]:
tensor2array = torch_data.numpy()
tensor2array

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
data = [-1, -2, 1, 2]

In [7]:
tensor = torch.FloatTensor(data)
tensor


-1
-2
 1
 2
[torch.FloatTensor of size 4]

In [8]:
np.abs(data)

array([1, 2, 1, 2])

In [9]:
torch.abs(data)

TypeError: torch.abs received an invalid combination of arguments - got (list), but expected (torch.FloatTensor source)

In [10]:
torch.abs(tensor)


 1
 2
 1
 2
[torch.FloatTensor of size 4]

In [11]:
tensor.sigmoid()


 0.2689
 0.1192
 0.7311
 0.8808
[torch.FloatTensor of size 4]

In [12]:
tensor * tensor


 1
 4
 1
 4
[torch.FloatTensor of size 4]

In [13]:
tensor.mm(tensor)

RuntimeError: invalid argument 2: dimension 1 out of range of 1D tensor at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/TH/generic/THTensor.c:24

In [14]:
tensor.matmul(tensor)

10.0

In [15]:
tensor.dot(tensor)

10.0

In [16]:
%load_ext version_information
%version_information torch, numpy, matplotlib

Software versions
Python 3.6.4 64bit [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
IPython 6.2.1
OS Linux 4.13.0 32 generic x86_64 with debian stretch sid
torch 0.3.0.post4
numpy 1.14.0
matplotlib 2.1.2
Sun Feb 11 19:29:00 2018 CST